config/routes.rb
Rails.application.routes.draw do
  get "products" => "products#index"
  get "/products/:name" => "products#show", as: :product
  get "users" => "users#index"
  get "users/new" => "users#new"
  post "users" => "users#create"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "products/new" => "products#new" 

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end
	def show
		# raise params.inspect
		#raise params[:name]
		@product = Product.find_by(name: "#{params[:name]}")
	end

	def new 
		@product = Product.new
	end

	def create
		@product = Product.new
	end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new 
	end

	def create
		user = User.find_by(email: params[:login][:email])

		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
			redirect_to users_path
		else
			render :new
		end
	end

	def destroy
		session.delete(:user_id)
		redirect_to login_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper

	def index
		@users = User.all 
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to users_path
		else
			render :new
		end
	end

	private

	def user_params
 		params.require(:user).permit(:name, :email, :password,:password_confirmation)
 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sunglasses</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<div>
Logged in as: [<%= current_user.name %>] <%= link_to 'LOG OUT', logout_path, method: :delete %>
</div>

<% else %> 
	<%= link_to "Sign Up", users_new_path %> | |
	<%= link_to "Log In", login_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<% @products.each do |product| %>


<div><%= product.name.upcase %></div>
<div><%= product.price %></div>
<div><% product.weight %></div>
<div><% product.inventory %></div>
<div>
<%= link_to "#{"View " + product.name + " Sunglasses"}", product_path(product.name) %>
</div>
<br>
<% end %>

app/views/products/new.html.erb
<h1>Add New Product</h1>
<%= form_for @product do |f| %>

<div>
<%= f.label :name %> <%= f.text_field :name %>
</div>
<div>
<%= f.label :price %> <%= f.text_field :price %>
</div>
<div>
<%= f.label :weight %> <%= f.text_field :weight %>
</div>
<div>
<%= f.label :inventory %> <%= f.integer_field :inventory %>
</div>
<div>
<%= f.label :description %> <%= f.text_field :description %>
</div>
<div>
<%= f.submit %>
</div>
<% end %>

app/views/products/show.html.erb
<div>
	The <%= @product.name %> sunglasses cost <%= @product.price %>
	<%= @product.description %>
</div>

	<br>

<div>
	<%= link_to "Back to Product List", products_path %>
</div>

app/views/users/index.html.erb
<%# if current_user %>
<div>
Logged in as: [<%#= current_user.name %>] <%#= link_to 'LOG OUT', logout_path, method: :delete %>
</div>

<%# else %> 
	<%#= link_to "Sign Up", users_new_path %>
	<%#= link_to "Log In", login_path %>
<%# end %>

<h1>All Users!</h1>
<%# lists the users on the index page #%>
<% @users.each do |user| %>
<%= user.name %>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>

<div>
<%= f.label :name %> <%= f.text_field :name %>
</div>
<div>
<%= f.label :email %> <%= f.text_field :email %>
</div>
<div>
<%= f.label :password %> <%= f.password_field :password %>
</div>
<div>
<%= f.label :password_confirmation %> <%= f.password_field :password_confirmation %>
</div>
<div>
<%= f.submit %>
</div>
<% end %>